dist: bionic

language: go

go:
  - 1.x
  - 1.12.x
  - 1.13.x

notifications:
  email: false

script:
  # Assert compilation
  - make build
  # Assert test suite
  - make test
  # Assert "go get" accessible
  - mkdir $HOME/go_get_test
  - cd $HOME/go_get_test
  - GO111MODULE=on go mod init go_get_test
  - 'go get -v github.com/codeactual/testecho/cmd/testecho@${TRAVIS_COMMIT}'
  - testecho --help
  # Attempt to invalidate Github's cached badge images
  - curl --silent --output hub-purge.sh https://raw.githubusercontent.com/codeactual/hub-purge/master/hub-purge.sh
  - chmod +x ./hub-purge.sh
  - ./hub-purge.sh codeactual/testecho
